"""Forensic fact tracer — NO production code changes.

Runs regression images through pipeline components and logs where facts
appear/disappear: MODEL → VERIFIED → CAPTION CANDIDATES → FINAL → QA.
"""

from __future__ import annotations

import re
from pathlib import Path

from app.startup.orchestrator import StartupOrchestrator
from core.contracts.pipeline import AnalysisOptions, PipelineRequest
from core.contracts.verified_evidence import ActivityEvidenceLevel
from language.assistant.entity_indexing import ordered_people
from language.assistant.evidence_packet import build_evidence_packet
from language.assistant.vision_assistant import VisionAssistant, VisionAssistantSession
from language.refinement.caption_arbitration import score_caption_candidate
from language.refinement.caption_coverage import ensure_salient_verified_coverage
from language.refinement.caption_sanity import sanitize_caption
from language.validation.caption_factuality import filter_unsupported_claims_verified

CASES = [
    ("horse_fire", Path("tmp/uploads/10815824_2997e03d76.jpg")),
    ("football", Path("tmp/uploads/141139674_246c0f90a1.jpg")),
    ("motorcycle", Path("tmp/uploads/143552829_72b6ba49d4.jpg")),
    ("bicycle", Path("tmp/uploads/191003284_1025b0fb7d.jpg")),
    ("kitchen", Path("tmp/coco_kitchen.jpg")),
    ("multi_clothing", Path("tmp/uploads/random_385406.jpg")),
]

QUESTIONS = [
    "How many people are visible?",
    "What is the person doing?",
    "What color clothing is the person wearing?",
    "What color clothing is the second person wearing?",
    "What color is the sports ball?",
    "What color is the horse?",
]


def _safe(s: object, n: int = 500) -> str:
    t = str(s or "").replace("\n", " ").strip()
    return t if len(t) <= n else t[: n - 3] + "..."


def main() -> None:
    out = Path("tmp/PRODUCTION_FACT_TRACE.md")
    lines: list[str] = [
        "# PRODUCTION FACT TRACE",
        "",
        "Forensic side-by-side: RAW → VERIFIED → CANDIDATES → FINAL → QA",
        "",
        "Generated by `tmp/forensic_fact_tracer.py` (no production code changes).",
        "",
    ]

    startup = StartupOrchestrator().run()
    orch = startup.context.main_controller.pipeline._orchestrator
    opts = AnalysisOptions(
        enable_gemma=False,
        competition_mode=False,
        enable_enhancement=False,
        enable_super_resolution=False,
        enable_sam2=False,
    )
    va = VisionAssistant()

    # Capture intermediates by wrapping analyze internals via monkeypatch in THIS process only.
    captured: dict = {}

    orig_natural = orch._natural_caption.generate if orch._natural_caption else None
    orig_semantic = orch._semantic_reasoning.synthesize
    orig_vlm = orch._run_vision_language

    def wrap_vlm(preprocessed, scene_context, completed, warnings):
        obs = orig_vlm(preprocessed, scene_context, completed, warnings)
        captured["vlm_raw_caption"] = getattr(obs, "raw_caption", None) if obs else None
        captured["vlm_observations"] = obs
        if obs is not None:
            caps = list(getattr(obs, "candidate_descriptions", ()) or ())
            captured["vlm_candidates"] = caps
        return obs

    def wrap_natural(preprocessed, understanding, context=None):
        text = orig_natural(preprocessed, understanding, context=context)
        captured["natural_paragraph"] = text
        return text

    def wrap_semantic(scene_context, observations):
        result = orig_semantic(scene_context, observations)
        captured["ollama_caption"] = (
            result.caption.text if result and result.caption else ""
        )
        captured["ollama_explanation"] = getattr(result, "scene_explanation", "") or ""
        return result

    orch._run_vision_language = wrap_vlm  # type: ignore[method-assign]
    if orig_natural:
        orch._natural_caption.generate = wrap_natural  # type: ignore[method-assign]
    orch._semantic_reasoning.synthesize = wrap_semantic  # type: ignore[method-assign]

    # Also intercept verified build by wrapping choose after analyze via stage re-run.
    # Re-extract from result + captured candidates.

    for name, image in CASES:
        lines.append(f"## CASE: `{name}`")
        lines.append(f"Image: `{image}`")
        lines.append("")
        captured.clear()
        if not image.exists():
            lines.append("**SKIP — missing image**")
            lines.append("")
            continue

        print(f"TRACE {name} {image}", flush=True)
        try:
            result = orch.analyze(PipelineRequest(image_path=image, options=opts))
        except Exception as exc:  # noqa: BLE001
            lines.append(f"**PIPELINE ERROR:** {exc}")
            lines.append("")
            continue

        ve = result.verified_evidence
        ctx = result.scene_context
        final_cap = (
            getattr(result.caption, "canonical_caption_en", None)
            or (result.caption.text if result.caption else "")
            or ""
        ).strip()

        # --- RAW DETECTIONS ---
        lines.append("### A. RAW YOLO detections (from scene_context.graph)")
        if ctx is None:
            lines.append("- (no scene_context)")
        else:
            people_raw = [
                n for n in ctx.graph.nodes if n.label.lower() in {"person", "man", "woman", "child"}
            ]
            lines.append(f"- raw person nodes: **{len(people_raw)}**")
            for n in ctx.graph.nodes[:20]:
                lines.append(
                    f"  - idx={n.index} label={n.label} area={n.bounding_box_area_ratio:.3f} zone={n.position_zone}"
                )
            if len(ctx.graph.nodes) > 20:
                lines.append(f"  - … +{len(ctx.graph.nodes) - 20} more")

        # --- ATTRIBUTES / COLORS ---
        lines.append("")
        lines.append("### B. Attribute colors (SceneContext)")
        if ctx is not None:
            color_attrs = [
                a
                for a in ctx.attributes.attributes
                if a.name
                in {
                    "color",
                    "dominant_color",
                    "clothing_color",
                    "shirt_color",
                    "pants_color",
                    "shoes_color",
                }
            ]
            for a in color_attrs[:40]:
                lines.append(f"  - obj#{a.object_index} {a.name}={a.value}")
            if not color_attrs:
                lines.append("  - (none)")

        # --- RELATIONS / HEURISTIC ACTIVITIES ---
        lines.append("")
        lines.append("### C. Relations + heuristic activities (SceneContext)")
        if ctx is not None:
            for r in ctx.graph.relations[:25]:
                lines.append(
                    f"  - rel {r.subject_index} --{r.relation_type}→ {r.object_index} conf={r.confidence:.2f}"
                )
            acts = list(ctx.activities.activities) if ctx.activities else []
            lines.append(f"- heuristic activities ({len(acts)}):")
            for a in acts:
                lines.append(
                    f"  - {a.activity!r} conf={a.confidence:.2f} "
                    f"nodes={a.supporting_node_indices} rels={a.supporting_relation_types}"
                )
            if not acts:
                lines.append("  - (none)")

        # --- VLM RAW ---
        lines.append("")
        lines.append("### D. VLM / BLIP-Florence RAW (before filters)")
        lines.append(f"- raw_caption: {_safe(captured.get('vlm_raw_caption'), 800)}")
        for i, c in enumerate(captured.get("vlm_candidates") or []):
            lines.append(f"- candidate[{i}]: {_safe(c, 400)}")

        # --- VERIFIED ---
        lines.append("")
        lines.append("### E. VerifiedSceneEvidence")
        if ve is None:
            lines.append("- **MISSING verified evidence**")
        else:
            narr_people = [
                e
                for e in ve.entities
                if e.narrative_safe and e.label.lower() in {"person", "man", "woman", "child"}
            ]
            all_people = [
                e for e in ve.entities if e.label.lower() in {"person", "man", "woman", "child"}
            ]
            lines.append(
                f"- people: raw_entities={len(all_people)} narrative_safe={len(narr_people)}"
            )
            for e in all_people:
                lines.append(
                    f"  - {e.entity_id} conf={e.confidence:.2f} narr_safe={e.narrative_safe} zone={e.position_zone}"
                )
            lines.append("- narrative color attrs:")
            for attr in ve.narrative_attributes():
                if "color" in attr.name:
                    lines.append(
                        f"  - {attr.entity_id}.{attr.name}={attr.value} "
                        f"conf={attr.confidence:.2f} status={attr.status.value}"
                    )
            lines.append("- activities:")
            for a in ve.activities:
                lines.append(
                    f"  - [{a.evidence_level.value}] {a.activity!r} "
                    f"narr={a.narrative_safe} qa={a.qa_safe} conf={a.confidence:.2f} "
                    f"entities={a.entity_ids} support={a.supporting_relations}"
                )
            if not ve.activities:
                lines.append("  - (none)")
            lines.append("- rejected activity/relation samples:")
            rej = [r for r in ve.rejected if r.predicate in {"activity", "relation"}][:15]
            for r in rej:
                lines.append(
                    f"  - REJECT {r.subject}.{r.predicate}={r.value!r} reason={r.reason}"
                )
            if not rej:
                lines.append("  - (none in sample)")

        # --- CANDIDATES + ARBITRATION ---
        lines.append("")
        lines.append("### F. Caption candidates + arbitration scores")
        natural = captured.get("natural_paragraph") or ""
        ollama = captured.get("ollama_caption") or ""
        refined = ""
        if result.caption and result.caption.sources:
            lines.append(f"- final sources tags: {result.caption.sources}")
        candidates = [
            ("natural", natural),
            ("ollama", ollama),
            ("final_locked", final_cap),
        ]
        if ve is not None:
            for label, text in candidates:
                if not (text or "").strip():
                    lines.append(f"- {label}: (empty)")
                    continue
                sc = score_caption_candidate(text, ve)
                lines.append(
                    f"- {label}: factuality={sc.factuality:.2f} coverage={sc.coverage:.2f} "
                    f"naturalness={sc.naturalness:.2f} total={sc.total:.2f} "
                    f"unsupported={sc.unsupported} rejected={sc.rejected} reason={sc.reason!r}"
                )
                lines.append(f"  text: {_safe(text, 450)}")
                filtered = filter_unsupported_claims_verified(text, ve)
                if filtered.strip() != sanitize_caption(text).strip():
                    lines.append(f"  after_factuality_filter: {_safe(filtered, 450)}")

        # --- FINAL + QA ---
        lines.append("")
        lines.append("### G. FINAL CAPTION")
        lines.append(_safe(final_cap, 700))
        lines.append("")
        lines.append("### H. QA answers (same verified packet)")
        packet = build_evidence_packet(
            ctx,
            canonical_caption_en=final_cap,
            verified_evidence=ve,
        )
        people_n = len(ordered_people(packet))
        lines.append(f"- ordered_people (QA SoT count): **{people_n}**")
        for q in QUESTIONS:
            session = VisionAssistantSession(image_key=name, evidence=packet)
            try:
                ans = va.answer(session, q)
            except Exception as exc:  # noqa: BLE001
                ans = f"ERROR: {exc}"
            # Skip irrelevant color Qs quietly in log but still show
            lines.append(f"- Q: {q}")
            lines.append(f"  A: {_safe(ans, 300)}")

        # --- INFORMATION LOSS TABLE ---
        lines.append("")
        lines.append("### I. Information-loss table")
        lines.append("| Fact | RAW/heuristic | VERIFIED | FINAL CAPTION | QA |")
        lines.append("|------|---------------|----------|---------------|----|")
        # people
        raw_p = len(people_raw) if ctx else 0
        ver_p = len(narr_people) if ve else 0
        cap_has_two = bool(re.search(r"\b(two|three|four|five|several|people|another person)\b", final_cap.lower()))
        qa_people = ""
        session = VisionAssistantSession(image_key=name, evidence=packet)
        try:
            qa_people = va.answer(session, "How many people are visible?")
        except Exception:
            qa_people = "?"
        lines.append(
            f"| people_count | {raw_p} | {ver_p} | "
            f"{'plural/cued' if cap_has_two else 'singular/unclear'} | {_safe(qa_people, 80)} |"
        )
        # activity
        heur = [a.activity for a in (ctx.activities.activities if ctx and ctx.activities else ())]
        ver_a = [
            f"{a.evidence_level.value}:{a.activity}(n={a.narrative_safe},q={a.qa_safe})"
            for a in (ve.activities if ve else ())
        ]
        session = VisionAssistantSession(image_key=name, evidence=packet)
        try:
            qa_act = va.answer(session, "What is the person doing?")
        except Exception:
            qa_act = "?"
        vlm = _safe(captured.get("vlm_raw_caption"), 120)
        act_pat = re.compile(r"\b(riding|holding|playing|leading|running)\b")
        cap_has_act = bool(act_pat.search(final_cap.lower()))
        lines.append(
            f"| activity | heur={heur[:3]!r} vlm≈{vlm!r} | {ver_a[:3]!r} | "
            f"{'has_action_verb' if cap_has_act else 'no_strong_verb'} | "
            f"{_safe(qa_act, 80)} |"
        )
        lines.append("")
        lines.append("---")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}", flush=True)


if __name__ == "__main__":
    main()
